#!/bin/bash
# Standalone package builder for luci-app-dae
# Supports both IPK (opkg) and APK (OpenWrt 25.x+) formats
#
# Usage:
#   ./build.sh           # auto-detect: APK if apk tool found, else IPK
#   ./build.sh ipk       # force IPK format
#   ./build.sh apk       # force APK format
#
# Output: output/luci-app-dae_1.0.0-1_all.{ipk,apk}

set -euo pipefail

VERSION="1.0.0"
RELEASE="1"
PKG_NAME="luci-app-dae"
ARCH="all"
BUILD_DIR=".build"
OUTPUT_DIR="output"

# ── Detect format ──────────────────────────────────────────────────
FORMAT="${1:-}"
if [ -z "$FORMAT" ]; then
    if command -v apk >/dev/null 2>&1; then
        FORMAT="apk"
    else
        FORMAT="ipk"
    fi
fi

echo "=== Building ${PKG_NAME} ${VERSION}-${RELEASE} (${FORMAT}) ==="

# Clean previous build
rm -rf "${BUILD_DIR}" "${OUTPUT_DIR}"
mkdir -p "${BUILD_DIR}/data" "${BUILD_DIR}/control" "${OUTPUT_DIR}"

# ── Copy package data ──────────────────────────────────────────────
echo "[1/4] Copying package files..."

# root/ → filesystem root overlay
if [ -d root ]; then
    cp -a root/* "${BUILD_DIR}/data/"
fi

# www/ → /www (LuCI web root)
if [ -d www ]; then
    mkdir -p "${BUILD_DIR}/data/www"
    cp -a www/* "${BUILD_DIR}/data/www/"
fi

# ── Fix permissions ────────────────────────────────────────────────
echo "[2/4] Setting permissions..."
[ -f "${BUILD_DIR}/data/etc/init.d/dae" ] && chmod 0755 "${BUILD_DIR}/data/etc/init.d/dae"
[ -f "${BUILD_DIR}/data/etc/uci-defaults/90_dae" ] && chmod 0755 "${BUILD_DIR}/data/etc/uci-defaults/90_dae"
[ -f "${BUILD_DIR}/data/usr/libexec/rpcd/luci.dae" ] && chmod 0755 "${BUILD_DIR}/data/usr/libexec/rpcd/luci.dae"
[ -f "${BUILD_DIR}/data/usr/share/dae/installer.sh" ] && chmod 0755 "${BUILD_DIR}/data/usr/share/dae/installer.sh"

# ── Create control/metadata files ──────────────────────────────────
echo "[3/4] Creating package metadata..."

INSTALLED_SIZE=$(du -sk "${BUILD_DIR}/data" | cut -f1)

# postinst script (shared by both formats)
write_postinst() {
    cat > "$1" <<'EOF'
#!/bin/sh
[ -z "$IPKG_INSTROOT" ] && [ -z "$APK_INSTROOT" ] || exit 0
[ -x /etc/uci-defaults/90_dae ] && /etc/uci-defaults/90_dae
/etc/init.d/rpcd reload 2>/dev/null || true
exit 0
EOF
    chmod 0755 "$1"
}

# prerm script
write_prerm() {
    cat > "$1" <<'EOF'
#!/bin/sh
[ -z "$IPKG_INSTROOT" ] && [ -z "$APK_INSTROOT" ] || exit 0
/etc/init.d/dae stop 2>/dev/null || true
exit 0
EOF
    chmod 0755 "$1"
}

# ── Build package ──────────────────────────────────────────────────
echo "[4/4] Building ${FORMAT^^}..."

cd "${BUILD_DIR}"

if [ "$FORMAT" = "apk" ]; then
    # ═══════════════════════════════════════════════════════════════
    # APK format (OpenWrt 25.x+)
    # Structure: file tree with .PKGINFO + install scripts
    # ═══════════════════════════════════════════════════════════════

    # .PKGINFO — APK metadata
    cat > data/.PKGINFO <<EOF
# Generated by build.sh
pkgname = ${PKG_NAME}
pkgver = ${VERSION}-${RELEASE}
arch = ${ARCH}
size = ${INSTALLED_SIZE}
origin = ${PKG_NAME}
maintainer = luci-app-dae contributors
license = AGPL-3.0
replaces = ${PKG_NAME}
provides = ${PKG_NAME}
# depend = luci-base
# depend = curl
# depend = unzip
# depend = ca-bundle
EOF

    # Triggers: run postinst after install
    mkdir -p data/.trigger
    write_postinst data/.trigger/postinst
    write_prerm data/.trigger/prerm

    # conffiles — preserve user modifications
    cat > data/.conffiles <<EOF
/etc/config/dae
/etc/dae/config.dae
EOF

    # Build APK (tar.gz with metadata)
    APK="../${OUTPUT_DIR}/${PKG_NAME}_${VERSION}-${RELEASE}_${ARCH}.apk"
    tar -czf "${APK}" -C data \
        --exclude='.trigger' \
        --exclude='.PKGINFO' \
        --exclude='.conffiles' \
        .
    # Rebuild with metadata files included
    tar -czf "${APK}" -C data .PKGINFO .trigger .conffiles \
        $(cd data && find . -not -name '.PKGINFO' -not -name '.trigger' -not -name '.conffiles' -not -name '.' | sed 's|^\./||')

    echo ""
    echo "=== Build complete ==="
    echo "Output: ${OUTPUT_DIR}/${PKG_NAME}_${VERSION}-${RELEASE}_${ARCH}.apk"
    echo "Size: $(du -h "${APK}" | cut -f1)"
    echo ""
    echo "Install: apk add --allow-untrusted ${PKG_NAME}_${VERSION}-${RELEASE}_${ARCH}.apk"

else
    # ═══════════════════════════════════════════════════════════════
    # IPK format (opkg, legacy)
    # Structure: debian-ar archive containing debian-binary + control.tar.gz + data.tar.gz
    # ═══════════════════════════════════════════════════════════════

    # control/control
    cat > control/control <<EOF
Package: ${PKG_NAME}
Version: ${VERSION}-${RELEASE}
Depends: libc
Source: package/${PKG_NAME}
License: AGPL-3.0
LicenseFiles: LICENSE
Section: luci
Architecture: ${ARCH}
Installed-Size: ${INSTALLED_SIZE}
Description: LuCI app for dae (with monitoring)
EOF

    # control/conffiles
    cat > control/conffiles <<EOF
/etc/config/dae
/etc/dae/config.dae
EOF

    write_postinst control/postinst
    write_prerm control/prerm

    # Assemble IPK
    tar -czf control.tar.gz -C control .
    tar -czf data.tar.gz -C data .
    echo "2.0" > debian-binary

    IPK="../${OUTPUT_DIR}/${PKG_NAME}_${VERSION}-${RELEASE}_${ARCH}.ipk"
    if command -v ar >/dev/null 2>&1; then
        ar rc "${IPK}" debian-binary control.tar.gz data.tar.gz
    else
        python3 -c "
import tarfile
ipk = '${IPK}'
files = ['debian-binary', 'control.tar.gz', 'data.tar.gz']
with tarfile.open(ipk, 'w:') as outer:
    for f in files:
        outer.add(f)
"
    fi

    echo ""
    echo "=== Build complete ==="
    echo "Output: ${OUTPUT_DIR}/${PKG_NAME}_${VERSION}-${RELEASE}_${ARCH}.ipk"
    echo "Size: $(du -h "${IPK}" | cut -f1)"
    echo ""
    echo "Install: opkg install ${PKG_NAME}_${VERSION}-${RELEASE}_${ARCH}.ipk"
fi

cd ..
rm -rf "${BUILD_DIR}"
