#!/bin/sh /etc/rc.common
# Copyright (C) 2023 Tianling Shen <cnsztl@immortalwrt.org>

USE_PROCD=1
START=99

extra_command "hot_reload" "Hot-reload service"

NAME="dae"
PROG="/usr/bin/dae"
CONF="/etc/dae/config.dae"
LOG="/var/log/dae/dae.log"

ensure_uci_config() {
    [ ! -f /etc/config/dae ] && touch /etc/config/dae
	if ! uci -q get dae.config >/dev/null 2>&1; then
		uci set dae.config=dae
		uci set dae.config.enabled='1'
		uci set dae.config.config_file='/etc/dae/config.dae'
        uci set dae.config.disable_waiting_network='0'
        uci set dae.config.enable_dae_log='1'
		uci set dae.config.log_maxbackups='1'
		uci set dae.config.log_maxsize='1'
		uci commit dae
	fi
}

start_service() {
    ensure_uci_config
    config_load $NAME
    mkdir -p /var/log/dae

	local enabled
	config_get_bool enabled "config" "enabled" "0"
	[ "$enabled" -eq "1" ] || return 1

    $PROG validate -c $CONF >> $LOG 2>&1 || return 1

	local log_maxbackups log_maxsize
	config_get log_maxbackups "config" "log_maxbackups" "1"
	config_get log_maxsize "config" "log_maxsize" "1"

	procd_open_instance "$NAME"
        procd_set_param command "$PROG" run
        procd_append_param command --config "$CONF"
		# procd_append_param command --disable-timestamp
		procd_append_param command --logfile "$LOG"
		procd_append_param command --logfile-maxbackups "$log_maxbackups"
		procd_append_param command --logfile-maxsize "$log_maxsize"

		procd_set_param limits core="unlimited"
		procd_set_param limits nofile="1000000 1000000"
		procd_set_param respawn
		# procd_set_param stdout 1
		procd_set_param stderr 1

	procd_close_instance
}

stop_service() {
	rm -rf "$LOG"
}

service_triggers() {
	procd_add_reload_trigger "$NAME"
}

hot_reload() {
	/etc/init.d/dae running && "$PROG" reload "$(cat /var/run/dae.pid)"
}
