#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99
STOP=10

readonly NAME="dae"
readonly PROG="/usr/bin/dae"
readonly CONF="/etc/dae/config.dae"
readonly LOG="/var/log/dae/dae.log"

EXTRA_COMMANDS="reload_config"
EXTRA_HELP="        reload_config   Reload $NAME config"

ensure_uci_config() {
    [ ! -f /etc/config/dae ] && touch /etc/config/dae
    if ! uci -q get dae.settings >/dev/null 2>&1; then
        uci set dae.settings=settings
        uci set dae.settings.enabled='1'
        uci set dae.settings.config_file='/etc/dae/config.dae'
        uci set dae.settings.disable_waiting_network='0'
        uci set dae.settings.enable_dae_log='1'
        uci set dae.settings.logfile_maxsize='1'
        uci set dae.settings.logfile_maxbackups='1'
        uci commit dae
    fi
}

start_service() {
    ensure_uci_config
    config_load $NAME
    mkdir -p /var/log/dae

    local enabled
    config_get_bool enabled "settings" "enabled" "0"
    [ "$enabled" -eq "1" ] || return 1

    $PROG validate -c $CONF >> $LOG 2>&1 || return 1

	local log_maxbackups log_maxsize
	config_get log_maxbackups "config" "log_maxbackups" "1"
	config_get log_maxsize "config" "log_maxsize" "1"

    procd_open_instance $NAME
        procd_set_param command $PROG
        procd_append_param command run --logfile $LOG -c $CONF
        procd_append_param command --disable-timestamp
        procd_append_param command --logfile-maxbackups "$log_maxbackups"
        procd_append_param command --logfile-maxsize "$log_maxsize"

        procd_set_param limits core="unlimited"
        procd_set_param limits nofile="1000000 1000000"
        procd_set_param respawn
        procd_set_param stderr 1
    procd_close_instance
}

restart() {
    stop
    start
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "$NAME"
}

reload_config() {
    $PROG reload
}
